name: CI
on: push
jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
          cache: 'yarn'
      - run: yarn setup
      - run: yarn lint --stream
      - run: yarn build --stream
      - run: yarn test --stream
