name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Lerna
        run: yarn global add lerna@6

      - run: yarn setup
      - run: yarn lint --stream
      - run: yarn build --stream
      - run: yarn test --stream
      - run: cp README.md packages/vue2 && cp README.md packages/vue3
      - run: cp -r packages/vue2/types packages/vue3
      - name: "Publish"
        if: contains('refs/heads/master', github.ref)
        run: lerna publish -y from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
