name: Publish NPM
on:
  release:
    types: [ created ]
jobs:
  build:
    name: Build & Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn setup
      - run: yarn lint --stream
      - run: yarn build --stream
      - run: yarn test --stream
      - run: lerna publish -y from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
